INPUT_ON_START_ONE_OUTPUT = 1
INPUT_ON_START_OUTPUT_ON_START = 2
INPUT_ON_START_OUTPUT_ON_DEMAND = 3
INPUT_ON_DEMAND_ONE_OUTPUT = 4
INPUT_ON_DEMAND_OUTPUT_ON_START = 5
INPUT_ON_DEMAND_OUTPUT_ON_DEMAND = 6
STACKED_ONE_OUTPUT = 7
